//OPERADORS LÓGICOS
//&& AND 
//|| OR (
//! NOT INVERTE O COMPARADOR OU DIFERENTE DE
//!= COMPARADOR INVERTIDO SIMPLES
//!== COMPARADOR INVERTIDO RESTRITO
//> MAIOR QUE 
//< MENOR QUE
// == COMPARADOR SIMPLES
//=== COMPARADOR RESTRITO
// >= MAIOR OU IGUAL A
// <= MENOR OU IGUAL A

let carrinho = "1500";
